"""Added portfolios

Revision ID: 08252727159b
Revises: 2e11b05126c9
Create Date: 2025-02-05 12:35:56.337215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08252727159b'
down_revision: Union[str, None] = '2e11b05126c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portfolio_stocks',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'stock_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_zar_good_date', 'zar_good', ['start_date'])
    op.create_unique_constraint('uq_zar_bad_date', 'zar_bad', ['start_date'])
    op.drop_constraint('uq_ticker_date', 'stock_data_history', type_='unique')
    op.drop_table('portfolio_stocks')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
