"""Fixed subscribers

Revision ID: 2e11b05126c9
Revises: 96a82b5f73ad
Create Date: 2025-02-04 12:00:48.233913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e11b05126c9'
down_revision: Union[str, None] = '96a82b5f73ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('token', sa.String(), nullable=True))
    op.add_column('subscribers', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('email_hash', sa.String(length=64), nullable=True))
    op.add_column('subscribers', sa.Column('web_hash', sa.String(length=64), nullable=True))
    op.add_column('subscribers', sa.Column('email_opened_count', sa.Integer(), nullable=True))
    op.add_column('subscribers', sa.Column('web_opened_count', sa.Integer(), nullable=True))
    op.add_column('subscribers', sa.Column('id_number', sa.String(), nullable=False))
    op.add_column('subscribers', sa.Column('black_listed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'subscribers', ['web_hash'])
    op.create_unique_constraint(None, 'subscribers', ['email_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='unique')
    op.drop_constraint(None, 'subscribers', type_='unique')
    op.drop_column('subscribers', 'black_listed')
    op.drop_column('subscribers', 'id_number')
    op.drop_column('subscribers', 'web_opened_count')
    op.drop_column('subscribers', 'email_opened_count')
    op.drop_column('subscribers', 'web_hash')
    op.drop_column('subscribers', 'email_hash')
    op.drop_column('subscribers', 'is_admin')
    op.drop_column('subscribers', 'token')
    op.drop_constraint('uq_ticker_date', 'stock_data_history', type_='unique')
    # ### end Alembic commands ###
