"""Add foreign keys and relationships for subscriptions

Revision ID: 32b9b6ffeb5a
Revises: ef3556e557fa
Create Date: 2025-01-29 16:53:30.430681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b9b6ffeb5a'
down_revision: Union[str, None] = 'ef3556e557fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_ticker_date', 'stock_data_history', ['ticker', 'date'])
    op.create_foreign_key(None, 'subscribers', 'subscriptions', ['subscription'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticker_name', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ticker_name', 'ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.drop_constraint('uq_ticker_date', 'stock_data_history', type_='unique')
    # ### end Alembic commands ###
