"""Added portfolio shares count with no null

Revision ID: 5108cb2a84f5
Revises: d3642eb2fb58
Create Date: 2025-02-18 21:48:28.835002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5108cb2a84f5'
down_revision: Union[str, None] = 'd3642eb2fb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_stocks', 'shares',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_stocks', 'shares',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
