"""Add foreign keys and relationships close runs

Revision ID: 96a82b5f73ad
Revises: 9fe150b10d54
Create Date: 2025-01-29 18:52:51.235601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a82b5f73ad'
down_revision: Union[str, None] = '9fe150b10d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_ticker_date', 'stock_data_history', ['ticker', 'date'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_ticker_date', 'stock_data_history', type_='unique')
    # ### end Alembic commands ###
    pass
