"""Add foreign keys and relationships for runs

Revision ID: 9fe150b10d54
Revises: 32b9b6ffeb5a
Create Date: 2025-01-29 18:50:14.479276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe150b10d54'
down_revision: Union[str, None] = '32b9b6ffeb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_ticker_date', 'stock_data_history', ['ticker', 'date'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_ticker_date', 'stock_data_history', type_='unique')
    # ### end Alembic commands ###
    pass