"""Added portfolio shares count

Revision ID: d3642eb2fb58
Revises: 08252727159b
Create Date: 2025-02-18 21:43:19.071433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3642eb2fb58'
down_revision: Union[str, None] = '08252727159b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_stocks', sa.Column('shares', sa.Integer()))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_stocks', 'shares')
    # ### end Alembic commands ###
