"""Add foreign keys and relationships to history and names

Revision ID: ef3556e557fa
Revises: b867cc1f262e
Create Date: 2025-01-29 16:36:14.504460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3556e557fa'
down_revision: Union[str, None] = 'b867cc1f262e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ticker_date', 'stock_data_history', type_='unique')
    #op.create_unique_constraint('uq_ticker_date', 'stock_data_history', ['ticker', 'date'])
    op.create_foreign_key(None, 'stock_data_history', 'stocks', ['ticker'], ['code'])
    op.create_foreign_key(None, 'technical_analysis', 'stocks', ['ticker'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticker_name', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ticker_name', 'ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'technical_analysis', type_='foreignkey')
    op.drop_constraint(None, 'stock_data_history', type_='foreignkey')
    #op.drop_constraint('uq_ticker_date', 'stock_data_history', type_='unique')
    #op.create_unique_constraint('unique_ticker_date', 'stock_data_history', ['ticker', 'date'])
    # ### end Alembic commands ###
