"""Add volume for commodities

Revision ID: 99f6b5224502
Revises: 4682726600ce
Create Date: 2025-04-10 18:58:25.817981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f6b5224502'
down_revision = '4682726600ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('subscription_functions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_research', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('portfolio', sa.Boolean(), nullable=False))
        batch_op.drop_column('new_web_reports')
        batch_op.drop_column('web_old_reports')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_functions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_old_reports', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('new_web_reports', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('portfolio')
        batch_op.drop_column('company_research')

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id_number',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)

    with op.batch_alter_table('htmlwebview', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subscriber_id')

    # ### end Alembic commands ###
